include: 
    package:very_good_analysis/analysis_options.yaml
#   package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.


# Uncomment to specify additional rules.
linter:
  rules:
    avoid_print: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
 