name: dart_isolate

environment:
    sdk: '^3.0.0'
  
discription: Learning module on dart isolate

publish_to: none

version: 1.0.0

dependencies:
    lints: ^2.1.1
    test: ^1.24.4
    very_good_analysis: ^5.0.0+1
