name: project3
description: expense Tracker app

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^1.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
