# this file uses firebase sdk , for security measure , firebase sdk setup files are
# not included in the git repo , install the firebase tools and configure firebase
# for this project to work

name: project9
description: Chat app 


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  transparent_image: ^2.0.1
  flutter_riverpod: ^2.3.6
  http: ^1.1.0
  uuid: ^3.0.7
  image_picker: ^1.0.2
  location: ^5.0.3
  google_maps_flutter: ^2.4.0
  path_provider: ^2.1.0
  path: any
  sqflite: ^2.3.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/chat.png
