name: NASA Project CI
on:
  push:
    branches: [ node ]
  pull_request:
    branches: [ node ]
  path:
    - node/'10. nasa-project ci-cd'

defaults:
  run:
    working-directory:
        description: Working directory to use
        type: string
        default: "./node/'10. nasa-project ci-cd'"

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
    
      - run: npm install

      - name: builds and run frontend
        run: npm run build --prefix client